### ISSUE TITLE
Does not support Select fields

### ISSUE THREAD

**Issue by ZakariaTlilani** [outer-web/filament-translatable-fields#12]
hello,
This package does not support Select fields when using relationship()

example:
`
                Select::make('attribute')
                    ->relationship('attribute', 'key')
                    ->translatable(),
`

This is the error that appears.
`
Typed property Filament\Forms\Components\Component::$container must not be accessed before initialization
`

**Comment by hamrak** [comment]
It's not a problem only with Select fields. I have TextInput in Repeater with relationship:

```php
Repeater::make('options')
                ->relationship('options')
                ->schema([
                    TextInput::make('code')->required()->regex('/^[a-z0-9]+$/')->unique(ignoreRecord: true),
                    TextInput::make('value')
                        ->nullable()
                        ->translatable(),
                ])
                ->defaultItems(0);
```

and i got this error too:

**Typed property Filament\Forms\Components\Component::$container must not be accessed before initialization**

**Comment by hamrak** [comment]
@SimonBroekaert  why do you need to set $clone->required(); ?

**Comment by ZakariaTlilani** [comment]
@SimonBroekaert @hamrak yes i noticed it too. This is a serious bug and must be fixed ASAP !!!

**Comment by SimonBroekaert** [comment]
Hi all (@ZakariaTlilani , @hamrak ),

Sorry for the late reply!

I work a full time job, a side job and these packages. So updates can take some time when the other two occupations are busy.

Thank you for figuring out it was due to the recently added `$clone->getValidationRules()`. I have removed this part of the code in **v.2.0.1**. So if you composer update, you should have the fixed code.

It was added recently due to this comment: https://github.com/outer-web/filament-translatable-fields/issues/5#issuecomment-2114045056 and I did not test all fields before commiting it. My bad. In the near future, I will be looking to add automated tests to this package (and my other packages), so that this will not happen again.

Thanks for your patience.

**Comment by karam-mustafa** [comment]
Has this error been resolved in `Forms\Components\Select` cases? I have upgraded to 2.0.1 and the issue still exists!
