### ISSUE TITLE
Class "OuterWeb\FilamentTranslatableFields\Filament\Plugins\FilamentTranslatableFieldsPlugin" not found

### ISSUE THREAD

**Issue by dkeyko** [outer-web/filament-translatable-fields#7]
Hi, I installed the plugin, specified it in PanelProvider, but it gives an error that the class was not found
![image](https://github.com/outer-web/filament-translatable-fields/assets/43813801/c3f2db53-59bf-40ae-88ee-b86d326f9cc5)

in PanelProvider file:
![image](https://github.com/outer-web/filament-translatable-fields/assets/43813801/856494f6-9f1d-4f63-9a21-fe982bebd6aa)

**Comment by marcelosantos89** [comment]
I did a fresh installation of filament and this occurs after installing the package

**Comment by SimonBroekaert** [comment]
Hi @marcelosantos89 and @dkeyko ,

There was a typo in the documentation regarding the namespace to use:

**Outerweb\FilamentTranslatableFields\Filament\Plugins\FilamentTranslatableFieldsPlugin**

instead of

OuterWeb\FilamentTranslatableFields\Filament\Plugins\FilamentTranslatableFieldsPlugin

I have updated the readme. Sorry for the overhead!
